### ISSUE TITLE
How to set first and last column sticky?

### ISSUE THREAD

**Issue by Govindbetterlives** [maxim-saplin/data_table_2#78] opened 2022-03-15 14:10 UTC
Hi,
How to set first and last column sticky?

Ex: - https://pub.dev/packages/lazy_data_table

**Comment by maxim-saplin** [comment] 2022-03-17 07:43
There's no such feature at the moment. Duplicate of https://github.com/maxim-saplin/data_table_2/issues/44 - currently there're no plans to approach that feature

**Closed by maxim-saplin** 2022-03-17 07:43 UTC
