### ISSUE TITLE
Row height adaptive

### ISSUE THREAD

**Issue by Sakura-1205** [maxim-saplin/data_table_2#232] opened 2023-10-24 03:15 UTC
I would like to ask if it is possible to make the height of the row adaptive. Sometimes the content of my row is not determined, and when there is too much content, it cannot be displayed all. If there is too little content, the height of these rows with little content will look strange given the height. I think I need a table that can adapt the height according to the content of the row, thank you!

**Comment by maxim-saplin** [comment] 2023-10-24 05:14
Hi, there are no adaptive cell width/height (determined baes on contents) cause it is one of the major details allowing to inplelemnt fixed parts in the first place.

No plans to change that.

**Comment by maxim-saplin** [comment] 2023-10-26 06:44
Duplicate of https://github.com/maxim-saplin/data_table_2/issues/103

**Closed by maxim-saplin** 2023-10-26 06:44 UTC
Labels: wontfix

**Comment by prolaymm** [comment] 2023-11-07 16:03
Sir @maxim-saplin  Why there is no dynamic support for DataCell?

**Comment by maxim-saplin** [comment] 2023-11-07 16:09
https://github.com/maxim-saplin/data_table_2/issues/103#issuecomment-1151959014
