### ISSUE TITLE
Horizontal Scroll is not active / visible when setting minWidth in DataTable2

### ISSUE THREAD

**Issue by RizaldiWiratama** [maxim-saplin/data_table_2#42] opened 2021-08-30 03:16 UTC
hey @maxim-saplin, i currently have issue with DataTable2, when having many data column and i set minWidth to 2000 the table is good but the horizontal scroll is not active/visible like this 

![image](https://user-images.githubusercontent.com/23089248/131279359-18929d5c-5dca-4702-a3b2-82b702e91e72.png)

but when i click tab in keyboard , it will go to next form and scroll to the right like this
![image](https://user-images.githubusercontent.com/23089248/131279830-980082e5-d6bb-4337-bc32-882727a4a058.png)

this is my code 
![image](https://user-images.githubusercontent.com/23089248/131279660-4a78a747-44fc-405a-9855-a49653b817e6.png)

currently i have flutter channel beta with latest update
![image](https://user-images.githubusercontent.com/23089248/131280167-508bfdf6-22e8-4451-a585-1cf0353778d7.png)

any suggestion why horizontal scroll is not visible? thank you

**Comment by maxim-saplin** [comment] 2021-08-30 08:07
What is the platform you build your app for (Web, Windows, etc.)?

**Comment by RizaldiWiratama** [comment] 2021-08-30 09:35
yea it is web and i use chrome browser

**Comment by maxim-saplin** [comment] 2021-08-30 10:21
Checked it on Web/Chrome/macOS, macOS and Linux. The issues seems to be unrelated to Beta or Stable channel and is specific to platforms' event tracking.
- macOS - both scroll direction work fine when scrolling with trackpad and when clicking and moving mouse cursor
- Linux - vertical scroll works fine with the trackpad, horizontal doesn't. Touching and holding curso allows spanning in any direction.
- Web/Chrome/macOS - cursor panning doesn't work. Vertical scroll with touchpad is OK, horizontal panning is inconsistent (e.g. when hovering over title both directions work find, when hovering over data rows horizontal scrolling is jugged) - seems there's some conflict between directions.

Unfortunately there're no workarounds at the moment, the issues need investigation.

**Comment by RizaldiWiratama** [comment] 2021-08-31 08:27
thanks for checking this issue @maxim-saplin , hope to see any workaround soon

**Comment by santhoshrao519** [comment] 2021-09-06 02:15
I'm also facing same like issue, please find a workaround for it. Thanks

**Comment by leoshusar** [comment] 2021-09-06 14:22
Isn't this related to [this](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) breaking change?
The workaround should be to add custom `ScrollBehavior` like this
```dart
class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => { 
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
    // etc.
  };
}
```

**Comment by RizaldiWiratama** [comment] 2021-09-07 08:18
@leoshusar thanks for information, that workaround make the table can be scroll by dragging with a mouse, but still horizontal scroll is not active

**Comment by maxim-saplin** [comment] 2021-09-08 06:24
@leoshusar thanks for pointing at the breaking change, though it is not related.

In fact the problem is related to the fact that Flutter doesn't have any scrolling widget that allows to scroll in both directions simultaneously and effectively allows panning. There's `InteractiveViewer` widget though it doesn't seem to be applicable here as it has mouse scroll events hardcoded to do zooming and panning is only possible with mouse pointer. Available scrolling solutions are one directional, when nesting `SingleChildScrollView` inside one another the very first scrolling direction is locked and the other is not available.

**Comment by maxim-saplin** [comment] 2021-09-08 07:17
@RizaldiWiratama 

Let's reiterate on the issue you have. In Chrome when you try to scroll horizontally DataTable2 (which is wider than browsre window) nothing happens, is thar correct?

Could you please check the sample on you machine? https://maxim-saplin.github.io/data_table_2/#/datatable2 - shrink the window until leftmost columns are hidden and try scrolling horizontally.

Pay attention  only one direction is available for scrolling, the very first initated. If you star scrolling horizaontally with fast swipes it is supposed to work.

![image](https://im6.ezgif.com/tmp/ezgif-6-6103c4bd89cf.gif)

**Comment by RizaldiWiratama** [comment] 2021-09-08 08:35
![image](https://user-images.githubusercontent.com/23089248/132472553-2d5796d0-7f57-4275-b615-433afe3d9505.png)

after test that sample, i can scroll horizontally and vertically the table with dragging mouse and yeah only one direction is available and the very first initiated.

but still **horizontal** **scrollbar** is not visible, i think i forgot to mention it clearly (i updated my last comment) that i need **scrollbar** to be visible like this ![image](https://user-images.githubusercontent.com/23089248/132474055-232e48fa-d46d-475b-8e59-23c07724eb50.png)

is there any workaround to make **horizontal scrollbar** visible @maxim-saplin ?

**Comment by maxim-saplin** [comment] 2021-09-08 09:29
I've just added the scrollbar to master branch. Could you please try referrencing it directly from the git repo in pubspec.yaml?

**Comment by RizaldiWiratama** [comment] 2021-09-08 09:54
Ok i try referrencing it like this
```
dependencies : 
 data_table_2:
    git:
      url: git://github.com/maxim-saplin/data_table_2.git
      ref: main
```

and the result is horizontal scrollbar is visible like this 
![image](https://user-images.githubusercontent.com/23089248/132487897-e0baecae-dfe9-4846-b941-66b54ddb40e3.png)

but i still can't scroll horizontally with that scrollbar

**Comment by maxim-saplin** [comment] 2021-09-08 14:53
Pushed a fix that allows scrolling via holding the scroll bar. Try now

**Comment by RizaldiWiratama** [comment] 2021-09-09 01:26
> Pushed a fix that allows scrolling via holding the scroll bar. Try now

already pub get and check but still can't scroll

i check the committed file already the latest
![image](https://user-images.githubusercontent.com/23089248/132606853-37e3d8d7-81a8-4ab6-af3e-f5eb68f63c3f.png)

**Comment by maxim-saplin** [comment] 2021-09-09 04:36
See in main branch,  not pub.dev

**Comment by RizaldiWiratama** [comment] 2021-09-09 07:11
i mean pub get in android studio, i already reference like this, still can't scroll
![image](https://user-images.githubusercontent.com/23089248/132639658-5fd6555f-98b5-45b9-a9d2-f5a374684eff.png)

**Comment by maxim-saplin** [comment] 2021-09-09 09:47
I beleive this shoud be enough to reference from the main branch:
```
data_table_2:
  git: https://github.com/maxim-saplin/data_table_2
```

Also try redownloading packages via `flutter pub cache repair`

Could you please also attach the video showing how you're trying to interact with the scroll bar? Here's how it look now:

![](https://im2.ezgif.com/tmp/ezgif-2-9327fbe88db7.gif)

**Comment by RizaldiWiratama** [comment] 2021-09-10 08:16
after referencing and redownloading packages via `flutter pub cache repair` the scrollbar is now active thanks @maxim-saplin for fixing this

**Comment by maxim-saplin** [comment] 2021-09-10 18:30
Great, will close the issue when the fix lands pub.dev

**Comment by vcenturion** [comment] 2021-09-30 03:14
I have the same problem, I run the example, using the library from the main repository but I can't scroll (horizontal or vertical) with the mouse.

- Flutter (Web)
- Chrome
- Windows

Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision 4cc385b4b8 (3 weeks ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

**Comment by maxim-saplin** [comment] 2021-11-05 08:19
I've pushed the newer version to pub.dev which now should display scroll bars whenever scrolling is initiated. Please let is you have any issues

**Closed** 2021-11-05 08:30 UTC
