### ISSUE TITLE
DataRow to Card/Other Widget

### ISSUE THREAD

**Issue by MalikSamiAwan** [maxim-saplin/data_table_2#59] opened 2021-12-08 11:34 UTC
Is there any way that we can data rows to cards in the small screen. E.g. mobiles etc

**Comment by maxim-saplin** [comment] 2021-12-09 13:40
Not sure I got your question

**Comment by maxim-saplin** [comment] 2022-03-09 06:45
Seems to be duplicate of #63

**Closed by maxim-saplin** 2022-03-09 06:45 UTC
