### ISSUE TITLE
Auto-size column width

### ISSUE THREAD

**Issue by paya-cz** [maxim-saplin/data_table_2#1] opened 2021-04-26 17:13 UTC
Nice project. However, I am really missing the ability to have each column autosize. Ideally, a way to set minWidth for each column to Auto. That way, if there is not enough horizontal space, the table would have a horizontal scrollbar and each column still renders nicely. If there is plenty of space, the columns would scale beyond minWidth per DataColumn2.size

**Comment by maxim-saplin** [comment] 2021-04-26 17:37
Thanks for the comments and interest in the package! You can tackle from problem from a different angle. DataTable already has minWidth set for the whole table: i.e. when there's not enough space in the container it stops shrinking, sizes to minWidth and display horizontal scroll. And the relative sizes of DataColumn2 (S, M and L) are essentialy Auto sizes (though not according to cells' contents). You can check how minWIdth works on the DataTabl2 sample by shrining window size: https://maxim-saplin.github.io/data_table_2/#/datatable2
Hope this helps.

**Comment by paya-cz** [comment] 2021-04-26 17:47
When I resize the window of the sample, I can see header cells being cut off. But yeah if I knew the data I want to display beforehand, I can hand-tune table minWidth with column relative sizes to make it look nice for that single particular dataset.

**Comment by maxim-saplin** [comment] 2021-04-26 18:15
Indeed, in the sample the minWidth is not enough to avoid clipping of column headings, deliberately chosen that width to demostrate that the widget clips whatever doesn't fit.
Auto sized columns is the default mode used by the stock DataTable (https://api.flutter.dev/flutter/rendering/IntrinsicColumnWidth-class.html) - it simply takes whatever room it needs based on individual cells' contents (and get's clipped if you don't bother with scroll containers).
I've thought of recreating the stock behaviour with intrinsic column widths, though didn't come up with a simple and performant solution and decided to stick to the current approach - 
prioritize the capability to fit all columns in the view while potentially not displaying them nicely and leave the auto size for latter.

**Comment by paya-cz** [comment] 2021-04-26 19:00
It seems that horizontalMargin eats space from first/last cells, instead of affecting all cells equally. This renders minWidth/cellSize approach difficult to manage, since size.S gives me a different width depending if it is set on the first cell or on a cell in the middle.

**Comment by paya-cz** [comment] 2021-04-26 19:04
Also since we have horizontalMargin, perhaps bottomMargin would make sense too? Recent iPhones do have a safeareainset at the bottom.

**Comment by maxim-saplin** [comment] 2021-04-26 21:26
> It seems that horizontalMargin eats space from first/last cells, instead of affecting all cells equally. This renders minWidth/cellSize approach difficult to manage, since size.S gives me a different width depending if it is set on the first cell or on a cell in the middle.

Thanks for pointing out the bug. The first and the last cells' widths were smaller by the horizontalMargin value. Checked in and publised the fix to pub.dev.

**Comment by maxim-saplin** [comment] 2021-04-26 21:33
> Also since we have horizontalMargin, perhaps bottomMargin would make sense too? Recent iPhones do have a safeareainset at the bottom.

I beleive this kind of cases are better solved by wrapping the table in widgets, such as Padding or SafeArea (https://api.flutter.dev/flutter/widgets/SafeArea-class.html). 
Besides, althoug the property is called horizontalMargin (the original name from stock widget), in fact it is not a margin in traditional sense - this is a padding of the first/last cell contents from the edge of the tabl, rather than the margin between outer edge of the table and its parent.

**Comment by paya-cz** [comment] 2021-04-27 06:31
> I beleive this kind of cases are better solved by wrapping the table in widgets, such as Padding or SafeArea (https://api.flutter.dev/flutter/widgets/SafeArea-class.html).

I generally agree, if the widget composability allowed this to be done well. I already tried to wrap the table in SafeArea.

Take a look below at what it looks like when you scroll to the middle of a long table - the red color is the SafeArea, colored via underlying Scaffold. Notice the position of the iPhone bottom horizontal line.

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-27 at 13 15 07](https://user-images.githubusercontent.com/10402560/116195359-4f0cc980-a75c-11eb-8a10-04ee9e31523d.png)

And this is what it should look like despite using SafeArea. The table content uses maximum screen real-estate until the user scrolls all the way to the bottom, at which point SafeArea engages. This can be solved well only if I can wrap the entire last row with SafeArea, or if the table embeds SafeArea itself.

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-27 at 13 16 37](https://user-images.githubusercontent.com/10402560/116195368-50d68d00-a75c-11eb-8e33-61519d1f2436.png)

I believe this is the reason why ListTile has SafeArea built-in, because it's a higher-level complex widget (like a DataTable) rather than something simple like a Padding widget.

**Comment by maxim-saplin** [comment] 2021-04-27 06:47
Could you please elaborate what's the expected behavior you'd like to get?
Beside, below is the sample running on 12 Pro emulator, all seems good without any SafeArea,Scaffold seems to be doing just fine clipping unsafe areas:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/7947027/116197033-e06c4380-a73c-11eb-8803-6416b99e6197.png">

**Comment by paya-cz** [comment] 2021-04-27 07:35
The proper iOS behavior is that there is no software clipping at all. Instead, when you scroll to the bottom, you can scroll a little bit past the content, so the content is located quite a bit above the horizontal touch line at the bottom of the screen (whatever it's called), and even above the rounded corners of the display. Take a look at the settings app:

First pic, scrolled to the middle of the scrollable area, so the content shows through everywhere, maximizing the visual information rather than clipping content. The only clipping done is by the display shape itself, notably the rounded corners.

![Screen Shot 2021-04-27 at 2 28 30 PM](https://user-images.githubusercontent.com/10402560/116202608-f988ea80-a764-11eb-96fe-248bf01f1022.png)

Second pic, scrolled all the way to the bottom of the scrollable area. There is extra space at the bottom of the scrollable area in order to allow the user to scroll the content a bit further and thus put the content above any kind of clipping that might be caused by the shape of the screen itself:

![Screen Shot 2021-04-27 at 2 28 59 PM](https://user-images.githubusercontent.com/10402560/116202649-06a5d980-a765-11eb-8fe0-428d3065bb2d.png)

**Comment by maxim-saplin** [comment] 2021-04-27 08:52
I've added bottomMargin to DataTable2 and have just published 2.0.2 to pub.dev - you're welcome to check)

**Comment by paya-cz** [comment] 2021-04-27 09:19
> I've added bottomMargin to DataTable2 and have just published 2.0.2 to pub.dev - you're welcome to check)

Perfect, I just tested it and with the combination of dataRowColor and headingRowColor, it looks really great and native! Thanks.

By the way, I have tested probably all sticky-header DataTable libs available for Flutter and yours is the one that looks the most polished and native.

**Comment by maxim-saplin** [comment] 2021-04-27 09:22
Thanks for the kind words, glad you liked it ;)

**Closed by maxim-saplin** 2021-04-27 09:22 UTC
